# generate_driver.ps1
# Generates and signs custom driver packages for the PS3 Eye camera and microphone interfaces

Set-Location -Path $PSScriptRoot

# 1. Update the video INF file to target MI_00
$infPath = "usb_device.inf"
$infContent = Get-Content -Path $infPath -Raw
$infContent = $infContent -replace 'DeviceID\s*=\s*"VID_1415&PID_2000"', 'DeviceID   = "VID_1415&PID_2000&MI_00"'
Set-Content -Path $infPath -Value $infContent -NoNewline

# 2. Create the CDF files
$cdfVideoPath = "usb_device.cdf"
$cdfVideoContent = @"
[CatalogHeader]
Name=usb_device.cat
PublicVersion=0x0000001
EncodingType=0x00010001
CATATTR1=0x10010001:OSAttr:2:6.0
CATATTR2=0x10010001:OSAttr:2:6.1
CATATTR3=0x10010001:OSAttr:2:6.2
CATATTR4=0x10010001:OSAttr:2:6.3
CATATTR5=0x10010001:OSAttr:2:10.0

[CatalogFiles]
<hash>usb_device.inf=usb_device.inf
<hash>WdfCoInstaller01011.dll=amd64\WdfCoInstaller01011.dll
<hash>WinUSBCoInstaller2.dll=amd64\winusbcoinstaller2.dll
"@
Set-Content -Path $cdfVideoPath -Value $cdfVideoContent

# 3. Run makecat.exe to generate the .cat file
$makecatPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\makecat.exe"
& $makecatPath -v $cdfVideoPath

# 4. Create and export a single self-signed certificate
$certSubject = "CN=PS3EyeVCam Driver Signing (autogenerated)"
$cert = New-SelfSignedCertificate -Type CodeSigning -Subject $certSubject -CertStoreLocation "Cert:\CurrentUser\My" -FriendlyName "PS3EyeVCam Driver Signing"

# Export the public key to usb_device.cer (used to install trusted certificate for the driver)
Export-Certificate -Cert $cert -FilePath "usb_device.cer" -Force

# 5. Sign the .cat file using signtool.exe
$signtoolPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe"
& $signtoolPath sign /s My /n "PS3EyeVCam Driver Signing (autogenerated)" /fd sha256 usb_device.cat

# 6. Clean up the temporary certificate from CurrentUser\My
Remove-Item -Path "Cert:\CurrentUser\My\$($cert.Thumbprint)" -Force

# Clean up temporary cdf files
Remove-Item -Path $cdfVideoPath -Force

Write-Host "Driver package successfully generated and signed for Video (MI_00)!" -ForegroundColor Green
