# generate_driver.ps1
# Generates and signs custom driver packages for the PS3 Eye camera and microphone interfaces

Set-Location -Path $PSScriptRoot

# Signing settings shared by all three packages.
#
# These certificates are self-signed, so the signer IS the root: without /tr the
# catalog signature dies with the certificate and pnputil refuses the package.
# Both /tr and a long -NotAfter are applied, because they fail independently.
# Regenerating changes every thumbprint -- expected, and needs no code change
# (the installer reads it from the embedded .cer), but the new packages must be
# install-tested on hardware.
$certNotAfter = (Get-Date).AddYears(20)
$timestampUrl = "http://timestamp.digicert.com"
$signtoolPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe"

# 1. Update the video INF file to target MI_00
$infPath = "usb_device.inf"
$infContent = Get-Content -Path $infPath -Raw
$infContent = $infContent -replace 'DeviceID\s*=\s*"VID_1415&PID_2000"', 'DeviceID   = "VID_1415&PID_2000&MI_00"'
Set-Content -Path $infPath -Value $infContent -NoNewline

# 2. Create the CDF files
$cdfVideoPath = "usb_device.cdf"
$cdfVideoContent = @"
[CatalogHeader]
Name=usb_device.cat
PublicVersion=0x0000001
EncodingType=0x00010001
CATATTR1=0x10010001:OSAttr:2:6.0
CATATTR2=0x10010001:OSAttr:2:6.1
CATATTR3=0x10010001:OSAttr:2:6.2
CATATTR4=0x10010001:OSAttr:2:6.3
CATATTR5=0x10010001:OSAttr:2:10.0

[CatalogFiles]
<hash>usb_device.inf=usb_device.inf
"@
Set-Content -Path $cdfVideoPath -Value $cdfVideoContent

# 3. Run makecat.exe to generate the .cat file
$makecatPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\makecat.exe"
& $makecatPath -v $cdfVideoPath

# 4. Create and export a single self-signed certificate
$certSubject = "CN=PSCam4Win Driver Signing (autogenerated)"
$cert = New-SelfSignedCertificate -Type CodeSigning -Subject $certSubject -CertStoreLocation "Cert:\CurrentUser\My" -FriendlyName "PSCam4Win Driver Signing" -NotAfter $certNotAfter

# Export the public key to usb_device.cer (used to install trusted certificate for the driver)
Export-Certificate -Cert $cert -FilePath "usb_device.cer" -Force

# 5. Sign the .cat file using signtool.exe (settings at the top of this script)
& $signtoolPath sign /s My /sha1 $($cert.Thumbprint) /fd sha256 /tr $timestampUrl /td sha256 usb_device.cat

# 6. Clean up the temporary certificate from CurrentUser\My
Remove-Item -Path "Cert:\CurrentUser\My\$($cert.Thumbprint)" -Force

# Clean up temporary cdf files
Remove-Item -Path $cdfVideoPath -Force

Write-Host "Driver package successfully generated and signed for Video (MI_00)!" -ForegroundColor Green

# ===========================================================================
# PS2 EyeToy (MI_00) — same self-signed WinUSB packaging as the PS3 Eye above.
# The inbox WinUSB.sys (MS-signed) is the actual kernel driver; only the INF
# catalog is self-signed, trusted via eyetoy_device.cer at install time.
# ===========================================================================

# 1. Create the EyeToy CDF
$cdfEyePath = "eyetoy_device.cdf"
$cdfEyeContent = @"
[CatalogHeader]
Name=eyetoy_device.cat
PublicVersion=0x0000001
EncodingType=0x00010001
CATATTR1=0x10010001:OSAttr:2:6.0
CATATTR2=0x10010001:OSAttr:2:6.1
CATATTR3=0x10010001:OSAttr:2:6.2
CATATTR4=0x10010001:OSAttr:2:6.3
CATATTR5=0x10010001:OSAttr:2:10.0

[CatalogFiles]
<hash>eyetoy_device.inf=eyetoy_device.inf
"@
Set-Content -Path $cdfEyePath -Value $cdfEyeContent

# 2. Generate the .cat (reuses $makecatPath from the PS3 block above)
& $makecatPath -v $cdfEyePath

# 3. Self-sign with a fresh code-signing cert, export the public key
$certEye = New-SelfSignedCertificate -Type CodeSigning -Subject $certSubject -CertStoreLocation "Cert:\CurrentUser\My" -FriendlyName "PSCam4Win Driver Signing" -NotAfter $certNotAfter
Export-Certificate -Cert $certEye -FilePath "eyetoy_device.cer" -Force
& $signtoolPath sign /s My /sha1 $($certEye.Thumbprint) /fd sha256 /tr $timestampUrl /td sha256 eyetoy_device.cat
Remove-Item -Path "Cert:\CurrentUser\My\$($certEye.Thumbprint)" -Force
Remove-Item -Path $cdfEyePath -Force

Write-Host "Driver package successfully generated and signed for EyeToy Video (MI_00)!" -ForegroundColor Green

# ===========================================================================
# PS4 Camera — WinUSB on the whole device for 0580 (boot) and 058A (legacy
# firmware), plus the MI_00 composite child for 058B (final 6.00+ firmware,
# which enumerates as an IAD/composite UVC device). Same self-signed WinUSB
# packaging as above.
# ===========================================================================

# 1. Create the PS4 CDF
$cdfPs4Path = "ps4cam_device.cdf"
$cdfPs4Content = @"
[CatalogHeader]
Name=ps4cam_device.cat
PublicVersion=0x0000001
EncodingType=0x00010001
CATATTR1=0x10010001:OSAttr:2:6.0
CATATTR2=0x10010001:OSAttr:2:6.1
CATATTR3=0x10010001:OSAttr:2:6.2
CATATTR4=0x10010001:OSAttr:2:6.3
CATATTR5=0x10010001:OSAttr:2:10.0

[CatalogFiles]
<hash>ps4cam_device.inf=ps4cam_device.inf
"@
Set-Content -Path $cdfPs4Path -Value $cdfPs4Content

# 2. Generate the .cat (reuses $makecatPath from the PS3 block above)
& $makecatPath -v $cdfPs4Path

# 3. Self-sign with a fresh code-signing cert, export the public key
$certPs4 = New-SelfSignedCertificate -Type CodeSigning -Subject $certSubject -CertStoreLocation "Cert:\CurrentUser\My" -FriendlyName "PSCam4Win Driver Signing" -NotAfter $certNotAfter
Export-Certificate -Cert $certPs4 -FilePath "ps4cam_device.cer" -Force
& $signtoolPath sign /s My /sha1 $($certPs4.Thumbprint) /fd sha256 /tr $timestampUrl /td sha256 ps4cam_device.cat
Remove-Item -Path "Cert:\CurrentUser\My\$($certPs4.Thumbprint)" -Force
Remove-Item -Path $cdfPs4Path -Force

Write-Host "Driver package successfully generated and signed for PS4 Camera (0580/058A/058B-MI_00)!" -ForegroundColor Green
